FROM mcr.microsoft.com/planetary-computer/python:latest

RUN echo "Running as ${NB_USER} user..."

ADD --chown=${NB_USER} src /app/src
ADD --chown=${NB_USER} src.egg-info /app/
ADD --chown=${NB_USER} setup.py /app/ 

WORKDIR /app

# Pip Install into Conda notebook environment
RUN /srv/conda/envs/notebook/bin/pip install -e .

WORKDIR ${HOME}