services:
    hub:
        image: mcr.microsoft.com/planetary-computer/python:latest
        container_name: hub
        environment:
            JUPYTERHUB_API_TOKEN: ${JUPYTERHUB_API_TOKEN}
            DASK_GATEWAY__AUTH__TYPE: "jupyterhub"
            DASK_GATEWAY__CLUSTER__OPTIONS__IMAGE: "mcr.microsoft.com/planetary-computer/python:latest"
            DASK_GATEWAY__ADDRESS: "https://pccompute.westeurope.cloudapp.azure.com/compute/services/dask-gateway"
            DASK_GATEWAY__PROXY_ADDRESS: "gateway://pccompute-dask.westeurope.cloudapp.azure.com:80"
        ports:
            - "8888:8888"
        volumes:
            - .:/home/jovyan
        command: jupyter lab --ip 0.0.0.0

    localserver:
        image: python:3.9-alpine
        container_name: localserver
        ports:
            - "8889:8889"
        volumes:
            - ./datasets:/opt/src/datasets
            - ./quickstarts:/opt/src/quickstarts
            - ./tutorials:/opt/src/tutorials
        command: python3 -m "http.server" 8889 -d /opt/src